-- DO NOT EDIT THIS FILE, EDIT THE CONFIG.LUA INSTEAD
-- DO NOT EDIT THIS FILE, EDIT THE CONFIG.LUA INSTEAD
-- DO NOT EDIT THIS FILE, EDIT THE CONFIG.LUA INSTEAD
AddEventHandler('onServerResourceStart', function(server)
    if (GetCurrentResourceName() ~= server) then
      return
    end
    local embed = {
        {
            ["color"] = color,
            ["title"] = messageTitle,
                ["url"] = messageUrl,
            ["description"] = message,
            ["footer"] = {
                ["text"] = footermessage,
            },
        }
    }
    PerformHttpRequest(webhookLink, function(err, text, headers) end, 'POST', json.encode({username = webhookName, embeds = embed, avatar_url = webhookAvatar}), { ['Content-Type'] = 'application/json' })
end)   
